name: Package - macOS

on:
  #push:
  #  branches: [ master ]

  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

jobs:
  macos:
    name: macOS Apps
    runs-on: macos-12
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.14
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags

      - name: Install build dependencies
        run: brew install cmake dylibbundler

      - name: Install library dependencies
        run: brew install sdl2 sdl12-compat sdl_mixer libpng physfs glew

      - name: Configure D1
        run: cmake -S d1 -B buildd1 -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build D1
        run: cmake --build buildd1

      - name: Configure D2
        run: cmake -S d2 -B buildd2 -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build D2
        run: cmake --build buildd2

      - name: Package
        run: ./contrib/packaging/macos/build_package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: '*.zip'
